"""
Parameterized OpenFOAM case generator for the plant module.

Takes a parameter dict, writes a complete buoyantSimpleFoam case
into a target directory.

This is the V1 case: sealed box, single fluid region, heat applied as
fixed heat flux on the floor, all other walls have external convection BC
to ambient. No fan, no vents, no fins yet — those come in V2 once V1
is converging cleanly.

Usage:
    from case_generator import generate_case
    case_dir = generate_case(
        params=dict(
            wall_thickness_mm=2.5,
            wall_k=0.20,
            ambient_C=25.0,
            heat_total_W=17.0,
            mesh_nx=36, mesh_ny=26, mesh_nz=20,
        ),
        target_dir="/tmp/my_case",
    )
"""

from pathlib import Path
from textwrap import dedent


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Plant module dimensions (mm) — fixed by spec
LX_MM, LY_MM, LZ_MM = 90.0, 65.0, 50.0

# ---------------------------------------------------------------------------
# True vent geometry (true_vents=True) — taken straight from the final CAD.
#
# Coordinates are in the INTERNAL cavity frame used by blockMesh:
#   x: 0..90 mm   (flow axis — fan on x=90 short wall)
#   y: 0..65 mm
#   z: 0..50 mm   (floor at z=0)
#
# - Fan: 50 mm 5 V fan (5010 frame) EXHAUSTING through a 45 mm dia opening
#   (the standard vent cut for a 50 mm frame; a full 50 mm hole cannot fit
#   the 50 mm-tall cavity), centred on the x=90 short wall (y=32.5, z=25).
# - Front intake (wall opposite the fan, x=0): 3 slots 50 x 5 mm,
#   horizontally centred (y 7.5..57.5), the slot group centred vertically
#   with 7.5 mm gaps -> slot rows z = 10–15 / 22.5–27.5 / 35–40.
# - Side intake (y=65 outward-facing long wall): 3 slots 40 x 5 mm,
#   centred (x 25..65), same vertical pattern.
# ---------------------------------------------------------------------------

FAN_CENTER_M = (0.090, 0.0325, 0.025)   # on x=90 face
FAN_RADIUS_M = 0.0225                    # 45 mm dia opening for the 50 mm fan

# (y_min, y_max, z_min, z_max) in metres, on the x=0 wall
FRONT_SLOTS_M = [
    (0.0075, 0.0575, 0.0100, 0.0150),
    (0.0075, 0.0575, 0.0225, 0.0275),
    (0.0075, 0.0575, 0.0350, 0.0400),
]

# (x_min, x_max, z_min, z_max) in metres, on the y=65 wall
SIDE_SLOTS_M = [
    (0.025, 0.065, 0.0100, 0.0150),
    (0.025, 0.065, 0.0225, 0.0275),
    (0.025, 0.065, 0.0350, 0.0400),
]

A_FAN_M2   = 3.14159265 * FAN_RADIUS_M**2                       # 1.590e-3
A_VENTS_M2 = (sum((y1-y0)*(z1-z0) for y0, y1, z0, z1 in FRONT_SLOTS_M)
              + sum((x1-x0)*(z1-z0) for x0, x1, z0, z1 in SIDE_SLOTS_M))  # 1.35e-3

# 50 mm 5 V axial fan characteristics (typical 5010 datasheet values,
# Sunon/Delta class), linear fan curve assumed:
#   free flow ~9 CFM and max static pressure ~40 Pa at 6000 rpm,
#   Q_free ∝ rpm, dP_max ∝ rpm² (fan affinity laws).
FAN_FREE_CFM_AT_6000 = 9.0
FAN_DP_MAX_PA_AT_6000 = 40.0
CFM_TO_M3S = 4.719e-4
RHO_AIR = 1.18      # kg/m3 at ~25 C
CD_VENT = 0.62      # sharp-edged slot discharge coefficient


def fan_operating_flow(p) -> float:
    """Fan operating-point volumetric flow (m^3/s) for true_vents mode.

    Intersects a linear fan curve dP = dP_max (1 - Q/Q_free) with the
    system curve dP = K Q^2, where K lumps the intake-slot vena-contracta
    loss and the fan-opening exit dynamic loss:
        K = 0.5 rho [ 1/(Cd A_vents)^2 + 1/A_fan^2 ]
    Solving K Q^2 + (dP_max/Q_free) Q - dP_max = 0 for Q > 0.

    At 6000 rpm this gives ~3.1e-3 m^3/s (~74 % of free flow) — the intake
    slots (1350 mm^2) are smaller than the fan opening (1590 mm^2), so they
    are the dominant restriction.
    """
    rpm = p.get("fan_rpm", 0.0)
    if rpm <= 1.0:
        return 0.0
    s = rpm / 6000.0
    Q_free = FAN_FREE_CFM_AT_6000 * CFM_TO_M3S * s
    dp_max = FAN_DP_MAX_PA_AT_6000 * s * s
    K = 0.5 * RHO_AIR * (1.0 / (CD_VENT * A_VENTS_M2)**2 + 1.0 / A_FAN_M2**2)
    a = dp_max / Q_free
    return (-a + (a * a + 4.0 * K * dp_max)**0.5) / (2.0 * K)


def _foam_header(cls: str, obj: str) -> str:
    return dedent(f"""\
        /*--------------------------------*- C++ -*----------------------------------*\\
        |  Generated by case_generator.py for term-project (MEP311s)              |
        \\*---------------------------------------------------------------------------*/
        FoamFile
        {{
            version     2.0;
            format      ascii;
            class       {cls};
            object      {obj};
        }}
        // ************************************************************************* //
        """)


# ---------------------------------------------------------------------------
# File writers
# ---------------------------------------------------------------------------

def write_topoSetDict(p, system_dir: Path) -> None:
    """Define cellZones for the actual heat-generating components.

    Locations (mm) chosen to mimic a typical breadboard layout:
      - resistor1:  small box on the floor, near front-left
      - resistor2:  small box on the floor, near front-right
      - mosfet:     small box on the floor, near back-center
    """
    content = _foam_header("dictionary", "topoSetDict") + dedent("""\
        actions
        (
            {
                name    resistor1Cells;
                type    cellSet;
                action  new;
                source  boxToCell;
                sourceInfo { box (0.020 0.025 0.000) (0.030 0.040 0.008); }
            }
            {
                name    resistor1Zone;
                type    cellZoneSet;
                action  new;
                source  setToCellZone;
                sourceInfo { set resistor1Cells; }
            }
            {
                name    resistor2Cells;
                type    cellSet;
                action  new;
                source  boxToCell;
                sourceInfo { box (0.060 0.025 0.000) (0.070 0.040 0.008); }
            }
            {
                name    resistor2Zone;
                type    cellZoneSet;
                action  new;
                source  setToCellZone;
                sourceInfo { set resistor2Cells; }
            }
            {
                name    mosfetCells;
                type    cellSet;
                action  new;
                source  boxToCell;
                sourceInfo { box (0.040 0.045 0.000) (0.050 0.055 0.012); }
            }
            {
                name    mosfetZone;
                type    cellZoneSet;
                action  new;
                source  setToCellZone;
                sourceInfo { set mosfetCells; }
            }
        );
        """)
    if p.get("true_vents"):
        content = content.rstrip().rstrip(");").rstrip() + "\n"
        cx, cy, cz = FAN_CENTER_M
        front_boxes = " ".join(
            f"({-0.001} {y0} {z0}) (0.001 {y1} {z1})"
            for y0, y1, z0, z1 in FRONT_SLOTS_M)
        side_boxes = " ".join(
            f"({x0} {LY_MM/1000.0 - 0.001} {z0}) ({x1} {LY_MM/1000.0 + 0.001} {z1})"
            for x0, x1, z0, z1 in SIDE_SLOTS_M)
        content += dedent(f"""\
            // --- true vent geometry: boundary faceSets for createPatch ---
            {{
                name    fanFaces;
                type    faceSet;
                action  new;
                source  patchToFace;
                sourceInfo {{ patch side_x1; }}
            }}
            {{
                name    fanFaces;
                type    faceSet;
                action  subset;
                source  cylinderToFace;
                sourceInfo
                {{
                    p1      ({cx - 0.001} {cy} {cz});
                    p2      ({cx + 0.001} {cy} {cz});
                    radius  {FAN_RADIUS_M};
                }}
            }}
            {{
                name    ventFrontFaces;
                type    faceSet;
                action  new;
                source  patchToFace;
                sourceInfo {{ patch side_x0; }}
            }}
            {{
                name    ventFrontFaces;
                type    faceSet;
                action  subset;
                source  boxToFace;
                sourceInfo {{ boxes ( {front_boxes} ); }}
            }}
            {{
                name    ventSideFaces;
                type    faceSet;
                action  new;
                source  patchToFace;
                sourceInfo {{ patch side_y1; }}
            }}
            {{
                name    ventSideFaces;
                type    faceSet;
                action  subset;
                source  boxToFace;
                sourceInfo {{ boxes ( {side_boxes} ); }}
            }}
        );
        """)
    (system_dir / "topoSetDict").write_text(content)


def write_createPatchDict(p, system_dir: Path) -> None:
    """Carve the fan disk and vent slots out of the wall patches.

    Runs after topoSet (which builds the faceSets); faces move from their
    original wall patch into the new openings. Remaining wall faces stay
    behind on side_x0 / side_x1 / side_y1.
    """
    content = _foam_header("dictionary", "createPatchDict") + dedent("""\
        pointSync false;

        patches
        (
            {
                name        fan;
                patchInfo   { type patch; }
                constructFrom set;
                set         fanFaces;
            }
            {
                name        ventFront;
                patchInfo   { type patch; }
                constructFrom set;
                set         ventFrontFaces;
            }
            {
                name        ventSide;
                patchInfo   { type patch; }
                constructFrom set;
                set         ventSideFaces;
            }
        );
        """)
    (system_dir / "createPatchDict").write_text(content)


def write_fvOptions(p, constant_dir: Path) -> None:
    """Apply localised volumetric heat to each component cellZone.

    Heat per zone:
      - resistor1, resistor2 share the resistor power equally
      - mosfet gets ~0.04 of total (small dissipation)
    """
    Q = p["heat_total_W"]
    Q_resistor = (Q - 0.7) * 0.5     # split remaining between two resistors
    Q_mosfet   = 0.7                 # ~0.6 W MOSFET + 0.1 W misc

    # Volume of each zone (m^3) - matches topoSetDict box dimensions
    V_res = 0.010 * 0.015 * 0.008    # 1.2e-6
    V_mos = 0.010 * 0.010 * 0.012    # 1.2e-6

    # Volumetric heat source = Q / V  (W/m^3)  -> applies as enthalpy source
    # Use volumeMode=absolute so total Q is preserved regardless of cell count
    content = _foam_header("dictionary", "fvOptions") + dedent(f"""\
        resistor1Heat
        {{
            type            scalarSemiImplicitSource;
            active          yes;
            selectionMode   cellZone;
            cellZone        resistor1Zone;
            volumeMode      absolute;
            sources
            {{
                h ({Q_resistor:.4f}  0);
            }}
        }}

        resistor2Heat
        {{
            type            scalarSemiImplicitSource;
            active          yes;
            selectionMode   cellZone;
            cellZone        resistor2Zone;
            volumeMode      absolute;
            sources
            {{
                h ({Q_resistor:.4f}  0);
            }}
        }}

        mosfetHeat
        {{
            type            scalarSemiImplicitSource;
            active          yes;
            selectionMode   cellZone;
            cellZone        mosfetZone;
            volumeMode      absolute;
            sources
            {{
                h ({Q_mosfet:.4f}  0);
            }}
        }}
        """)
    (constant_dir / "fvOptions").write_text(content)


def write_blockMeshDict(p, system_dir: Path) -> None:
    """6-patch mesh: floor, ceiling, side_x0, side_x1, inlet (y=0), outlet (y=Ly).

    inlet/outlet are always type=patch so we can switch their BCs between
    'closed wall' (sealed config, fan_rpm=0) and 'fan/vent open' (fan_rpm>0)
    without changing the mesh.

    true_vents mode: all six faces are walls named floor / ceiling /
    side_x0 / side_x1 / side_y0 / side_y1; the fan disk and vent slots are
    carved out of side_x1 / side_x0 / side_y1 afterwards by
    topoSet + createPatch.
    """
    nx, ny, nz = p["mesh_nx"], p["mesh_ny"], p["mesh_nz"]
    if p.get("true_vents"):
        y0_name, y0_type = "side_y0", "wall"
        y1_name, y1_type = "side_y1", "wall"
    else:
        y0_name, y0_type = "inlet", "patch"
        y1_name, y1_type = "outlet", "patch"
    content = _foam_header("dictionary", "blockMeshDict") + dedent(f"""\
        scale   0.001;

        vertices
        (
            (   0     0     0)
            ({LX_MM}     0     0)
            ({LX_MM}  {LY_MM}     0)
            (   0  {LY_MM}     0)
            (   0     0  {LZ_MM})
            ({LX_MM}     0  {LZ_MM})
            ({LX_MM}  {LY_MM}  {LZ_MM})
            (   0  {LY_MM}  {LZ_MM})
        );

        blocks
        (
            hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)
        );

        edges ();

        boundary
        (
            floor
            {{
                type wall;
                faces ( (0 3 2 1) );
            }}
            ceiling
            {{
                type wall;
                faces ( (4 5 6 7) );
            }}
            {y0_name}
            {{
                type {y0_type};
                faces ( (0 1 5 4) );
            }}
            {y1_name}
            {{
                type {y1_type};
                faces ( (3 7 6 2) );
            }}
            side_x0
            {{
                type wall;
                faces ( (0 4 7 3) );
            }}
            side_x1
            {{
                type wall;
                faces ( (1 2 6 5) );
            }}
        );

        mergePatchPairs ();
        """)
    (system_dir / "blockMeshDict").write_text(content)


SIGMA = 5.67e-8       # Stefan-Boltzmann (W/m^2 K^4)


# Discrete wall materials -- the BO sees `wall_material` as an integer
# 0, 1, 2 and translates to the (k, density g/cm3, cost EGP/cm3) tuple.
WALL_MATERIALS = {
    0: dict(name="PLA",      k=0.20, rho=1.40, cost_per_cm3=0.6,  emiss=0.90),
    1: dict(name="Acrylic",  k=0.19, rho=1.18, cost_per_cm3=0.4,  emiss=0.94),
    2: dict(name="Aluminum", k=200.,  rho=2.70, cost_per_cm3=4.0,  emiss=0.10),
}


def material_props(idx: int):
    """Resolve integer wall_material index to material properties.

    Caller may pass a float (BO output) -- we round to nearest integer.
    """
    i = int(round(idx))
    return WALL_MATERIALS[max(0, min(i, len(WALL_MATERIALS) - 1))]


def _h_radiation(T_amb_K: float, T_s_estimate_K: float = 320.0,
                 emissivity: float = 0.9) -> float:
    """Linearized radiation heat-transfer coefficient.

        q_rad = epsilon * sigma * (T_s^4 - T_amb^4)
              ~ h_rad * (T_s - T_amb)   where
        h_rad = epsilon * sigma * (T_s + T_amb) * (T_s^2 + T_amb^2)

    Using a representative T_s = 320 K (47 C wall surface). For typical
    plastic / paint emissivity epsilon = 0.9. Aluminum bare = 0.05; if
    aluminum walls are chosen, the caller should pass emissivity=0.05.
    """
    return emissivity * SIGMA * (T_s_estimate_K + T_amb_K) * (
        T_s_estimate_K**2 + T_amb_K**2
    )


def _wall_emissivity(p) -> float:
    """Look up emissivity from WALL_MATERIALS using the design parameters.

    Prefers the integer `wall_material` index (BO output). Falls back to
    matching on `wall_k` if only k is given (legacy callers).
    """
    if "wall_material" in p:
        return material_props(p["wall_material"])["emiss"]
    k = p.get("wall_k", 0.20)
    # Fallback: match k to material
    for entry in WALL_MATERIALS.values():
        if abs(entry["k"] - k) < 1e-3:
            return entry["emiss"]
    return 0.10 if k > 50 else 0.90


def _compute_h_eff(p):
    """Effective wall-to-ambient h, accounting for:
        - external natural convection (h_ext)
        - wall conduction (wall_thickness_mm, wall_k)
        - external radiation (linearised, depends on emissivity & T_amb)
        - external heat sink as a *parallel* cooling path (hs_R_external)
    Returns h_eff_floor, h_eff_walls (W/m2.K).

    Floor differs because when fins are present they're attached at the
    floor (where heat is generated), so the floor gets an effective h
    enhancement proportional to the added finned surface area.
    """
    h_ext = p.get("h_ext", 8.0)
    R_wall = (p["wall_thickness_mm"] / 1000.0) / p["wall_k"]

    # Native: external convection in series with wall conduction.
    h_native_conv = 1.0 / (1.0 / h_ext + R_wall)

    # Radiation in PARALLEL with convection to ambient at the outer wall
    # surface. Adds ~5 W/m2.K for plastic at ~50 C; ~0.5 for bare metal.
    eps = _wall_emissivity(p)
    T_amb_K = p["ambient_C"] + 273.15
    h_rad = _h_radiation(T_amb_K, T_s_estimate_K=320.0, emissivity=eps)
    h_native = h_native_conv + h_rad

    # External heat sink: real geometry-based R from fin array attached to
    # one outer wall. User specifies hs_fin_count and hs_fin_height_mm.
    # Skip if either is zero.
    hs_fin_count = p.get("hs_fin_count", 0)
    hs_fin_height_mm = p.get("hs_fin_height_mm", 0)
    A_ext = 2 * (LX_MM*LY_MM + LX_MM*LZ_MM + LY_MM*LZ_MM) * 1e-6  # m^2
    if hs_fin_count > 0 and hs_fin_height_mm > 0:
        # External fin array on one wall (e.g. side_x1 = 65*50 = 3250 mm^2)
        import math
        k_hs = 200.0   # aluminum
        t_hs = 0.0015  # 1.5 mm fin thickness
        L_hs = hs_fin_height_mm / 1000.0
        m_hs = (2.0 * h_ext / (k_hs * t_hs)) ** 0.5
        eta_hs = math.tanh(m_hs * L_hs) / (m_hs * L_hs) if m_hs * L_hs > 1e-3 else 1.0
        wall_width = LY_MM / 1000.0  # 0.065 m
        A_hs_fins = hs_fin_count * 2.0 * L_hs * wall_width
        # Total HS surface = base + fins
        A_hs_base = (LY_MM * LZ_MM) * 1e-6  # one side wall
        A_hs_total = A_hs_base + eta_hs * A_hs_fins
        # Effective HS conductance = h_ext * A_hs_total. Convert to area-normalised h_HS.
        h_HS = (h_ext * A_hs_total) / A_ext
    else:
        h_HS = 0.0
    h_walls = h_native + h_HS

    # Fin enhancement on the floor (where components live).
    # Real fin formula:  q = h * eta_f * A_fin * dT
    # eta_f = tanh(m*L) / (m*L)   where m = sqrt(2*h / (k_fin * t_fin))
    # We use aluminum fins (k=200) with t = 1 mm, attached to component zones.
    fin_count = p.get("fin_count", 0)
    fin_height_mm = p.get("fin_height_mm", 0)
    fin_thickness_mm = p.get("fin_thickness_mm", 1.0)
    if fin_count > 0 and fin_height_mm > 0:
        k_fin = 200.0
        t_fin = fin_thickness_mm / 1000.0
        L_fin = fin_height_mm / 1000.0
        m = (2.0 * h_native / (k_fin * t_fin)) ** 0.5
        ml = m * L_fin
        # Avoid div-by-zero
        eta = max(0.05, (1.0 if ml < 0.01 else ((1.0 - (-2.0 * ml).real) / (1.0))))
        # Use proper tanh formula
        import math
        eta = math.tanh(ml) / ml if ml > 1e-3 else 1.0
        # Fin contributes extra surface area  A_fin = N * 2 * L * width (use 90mm)
        A_fin = fin_count * 2.0 * L_fin * 0.090
        # Increase floor effective h to account for fin extra cooling surface
        # A_floor_geo = 0.090 * 0.065 = 0.00585 m^2
        A_floor = 0.090 * 0.065
        fin_h_boost = (eta * A_fin / A_floor) * h_native
        h_floor = h_native + fin_h_boost + h_HS
    else:
        h_floor = h_native + h_HS

    return h_floor, h_walls


def write_T(p, zero_dir: Path) -> None:
    T_amb_K = p["ambient_C"] + 273.15
    h_floor, h_eff = _compute_h_eff(p)

    fan_on = p.get("fan_rpm", 0) > 1.0
    if fan_on:
        # Inlet brings in ambient air, outlet lets air leave at internal T
        inlet_t = (
            f"            type            fixedValue;\n"
            f"            value           uniform {T_amb_K:.2f};"
        )
        outlet_t = (
            f"            type            inletOutlet;\n"
            f"            inletValue      uniform {T_amb_K:.2f};\n"
            f"            value           uniform {T_amb_K:.2f};"
        )
    else:
        # Sealed: inlet/outlet behave like external walls
        wall_bc = (
            f"            type            externalWallHeatFluxTemperature;\n"
            f"            mode            coefficient;\n"
            f"            Ta              uniform {T_amb_K:.2f};\n"
            f"            h               uniform {h_eff:.4f};\n"
            f"            kappaMethod     fluidThermo;\n"
            f"            value           uniform {T_amb_K:.2f};"
        )
        inlet_t = wall_bc
        outlet_t = wall_bc

    content = _foam_header("volScalarField", "T") + dedent(f"""\
        dimensions      [0 0 0 1 0 0 0];
        internalField   uniform {T_amb_K:.2f};

        boundaryField
        {{
            floor
            {{
                type            externalWallHeatFluxTemperature;
                mode            coefficient;
                Ta              uniform {T_amb_K:.2f};
                h               uniform {h_floor:.4f};
                kappaMethod     fluidThermo;
                value           uniform {T_amb_K:.2f};
            }}
            ceiling
            {{
                type            externalWallHeatFluxTemperature;
                mode            coefficient;
                Ta              uniform {T_amb_K:.2f};
                h               uniform {h_eff:.4f};
                kappaMethod     fluidThermo;
                value           uniform {T_amb_K:.2f};
            }}
            side_x0
            {{
                type            externalWallHeatFluxTemperature;
                mode            coefficient;
                Ta              uniform {T_amb_K:.2f};
                h               uniform {h_eff:.4f};
                kappaMethod     fluidThermo;
                value           uniform {T_amb_K:.2f};
            }}
            side_x1
            {{
                type            externalWallHeatFluxTemperature;
                mode            coefficient;
                Ta              uniform {T_amb_K:.2f};
                h               uniform {h_eff:.4f};
                kappaMethod     fluidThermo;
                value           uniform {T_amb_K:.2f};
            }}
            inlet
            {{
{inlet_t}
            }}
            outlet
            {{
{outlet_t}
            }}
        }}
        """)
    (zero_dir / "T").write_text(content)


def _fan_velocity(p) -> float:
    """Convert fan_rpm to inlet face velocity (m/s).

    Calibrated from 30mm 5V fan datasheets:
      ~6 CFM at 4000 rpm  =>  0.0028 m^3/s  /  0.0045 m^2 inlet  =>  0.63 m/s
    Linear in rpm.

    Vent area effect: smaller vent area restricts flow. Vent fraction is
    bounded [0.1, 1.0] of full inlet face. A small vent throttles the fan.
    """
    rpm = p.get("fan_rpm", 0.0)
    full_vent_mm2 = LX_MM * LZ_MM   # inlet face area = 90 * 50 = 4500 mm^2
    vent_area_mm2 = p.get("vent_area_mm2", full_vent_mm2)
    vent_frac = max(0.1, min(1.0, vent_area_mm2 / full_vent_mm2))
    return 0.63 * (rpm / 4000.0) * vent_frac


def write_U(p, zero_dir: Path) -> None:
    fan_on = p.get("fan_rpm", 0) > 1.0
    if fan_on:
        v = _fan_velocity(p)
        # Inlet on y=0 face -> velocity points in +y direction (into the box)
        inlet_u = (
            f"            type            fixedValue;\n"
            f"            value           uniform (0 {v:.4f} 0);"
        )
        outlet_u = (
            f"            type            inletOutlet;\n"
            f"            inletValue      uniform (0 0 0);\n"
            f"            value           uniform (0 0 0);"
        )
    else:
        inlet_u = "            type            noSlip;"
        outlet_u = "            type            noSlip;"

    content = _foam_header("volVectorField", "U") + dedent(f"""\
        dimensions      [0 1 -1 0 0 0 0];
        internalField   uniform (0 0 0);

        boundaryField
        {{
            floor   {{ type noSlip; }}
            ceiling {{ type noSlip; }}
            side_x0 {{ type noSlip; }}
            side_x1 {{ type noSlip; }}
            inlet
            {{
{inlet_u}
            }}
            outlet
            {{
{outlet_u}
            }}
        }}
        """)
    (zero_dir / "U").write_text(content)


def write_p(p, zero_dir: Path) -> None:
    fan_on = p.get("fan_rpm", 0) > 1.0
    inout = (
        "        inlet   { type calculated; value uniform 100000; }\n"
        "        outlet  { type calculated; value uniform 100000; }"
    ) if not fan_on else (
        "        inlet   { type calculated; value uniform 100000; }\n"
        "        outlet  { type calculated; value uniform 100000; }"
    )
    content = _foam_header("volScalarField", "p") + dedent(f"""\
        dimensions      [1 -1 -2 0 0 0 0];
        internalField   uniform 100000;

        boundaryField
        {{
            floor   {{ type calculated; value uniform 100000; }}
            ceiling {{ type calculated; value uniform 100000; }}
            side_x0 {{ type calculated; value uniform 100000; }}
            side_x1 {{ type calculated; value uniform 100000; }}
{inout}
        }}
        """)
    (zero_dir / "p").write_text(content)


def write_p_rgh(p, zero_dir: Path) -> None:
    fan_on = p.get("fan_rpm", 0) > 1.0
    if fan_on:
        inlet_p = "            type fixedFluxPressure; value uniform 100000;"
        outlet_p = "            type totalPressure; p0 uniform 100000;"
    else:
        inlet_p = "            type fixedFluxPressure; value uniform 100000;"
        outlet_p = "            type fixedFluxPressure; value uniform 100000;"

    content = _foam_header("volScalarField", "p_rgh") + dedent(f"""\
        dimensions      [1 -1 -2 0 0 0 0];
        internalField   uniform 100000;

        boundaryField
        {{
            floor   {{ type fixedFluxPressure; value uniform 100000; }}
            ceiling {{ type fixedFluxPressure; value uniform 100000; }}
            side_x0 {{ type fixedFluxPressure; value uniform 100000; }}
            side_x1 {{ type fixedFluxPressure; value uniform 100000; }}
            inlet
            {{
{inlet_p}
            }}
            outlet
            {{
{outlet_p}
            }}
        }}
        """)
    (zero_dir / "p_rgh").write_text(content)


def write_turbulence_fields(p, zero_dir: Path) -> None:
    """k, omega, nut, alphat, epsilon for inlet/outlet/wall patches.

    NOTE: inlet/outlet are patch-type, not wall-type, so they cannot
    use wall functions. For sealed mode we use zeroGradient on them
    (they're physically closed but we keep them as patch type for
    BC flexibility when the fan is on).
    """
    fan_on = p.get("fan_rpm", 0) > 1.0
    walls = ("floor", "ceiling", "side_x0", "side_x1")
    inout = ("inlet", "outlet")  # always patch type

    def block(wall_bc: str, inlet_bc: str, outlet_bc: str) -> str:
        lines = []
        for w in walls:
            lines.append(f"            {w} {{ {wall_bc} }}")
        for io in inout:
            bc = inlet_bc if io == "inlet" else outlet_bc
            lines.append(f"            {io} {{ {bc} }}")
        return "\n".join(lines)

    # Wall treatment chosen for the y+ regime of this mesh.
    # Fine mesh (110×80×60 over 90×65×50 mm) → first-cell y+ ≈ 2, which is the
    # viscous-sublayer / buffer-layer range. Low-Re wall functions are the
    # correct choice; standard wall functions (kqRWallFunction, nutkWallFunction)
    # require y+ ≥ 30 and would mis-predict near-wall turbulence here.
    fields = {
        "k": (
            "[0 2 -2 0 0 0 0]", "0.001",
            block("type kLowReWallFunction; value uniform 1e-10;",
                  "type fixedValue; value uniform 0.001;",
                  "type inletOutlet; inletValue uniform 0.001; value uniform 0.001;"),
        ),
        "omega": (
            "[0 0 -1 0 0 0 0]", "1.0",
            # omegaWallFunction is Menter-blended — valid across the full y+
            # range from viscous sublayer to log-law region.
            block("type omegaWallFunction; value uniform 1.0;",
                  "type fixedValue; value uniform 1.0;",
                  "type inletOutlet; inletValue uniform 1.0; value uniform 1.0;"),
        ),
        "epsilon": (
            "[0 2 -3 0 0 0 0]", "0.01",
            block("type epsilonWallFunction; value uniform 0.01;",
                  "type fixedValue; value uniform 0.01;",
                  "type inletOutlet; inletValue uniform 0.01; value uniform 0.01;"),
        ),
        "nut": (
            "[0 2 -1 0 0 0 0]", "0",
            block("type nutLowReWallFunction; value uniform 0;",
                  "type calculated; value uniform 0;",
                  "type calculated; value uniform 0;"),
        ),
        "alphat": (
            "[1 -1 -1 0 0 0 0]", "0",
            block("type compressible::alphatWallFunction; Prt 0.85; value uniform 0;",
                  "type calculated; value uniform 0;",
                  "type calculated; value uniform 0;"),
        ),
    }

    for name, (dims, init, body) in fields.items():
        content = _foam_header("volScalarField", name) + dedent(f"""\
            dimensions      {dims};
            internalField   uniform {init};
            boundaryField
            {{
{body}
            }}
            """)
        (zero_dir / name).write_text(content)


# ---------------------------------------------------------------------------
# true_vents field writers — patches:
#   walls : floor, ceiling, side_x0, side_x1, side_y0, side_y1
#   open  : fan (x=90 disk), ventFront (x=0 slots), ventSide (y=65 slots)
#
# fan ON  : fan = prescribed exhaust flow (flowRateInletVelocity, negative),
#           vents = passive pressure inlets (prghTotalPressure).
# fan OFF : fan = blocked (stopped blades ≈ wall), vents stay open →
#           buoyancy-driven natural draft through the slots. This is the
#           physically correct fan-off configuration of the actual CAD
#           (the old model used a pseudo-sealed box instead).
# ---------------------------------------------------------------------------

_TV_WALLS = ("floor", "ceiling", "side_x0", "side_x1", "side_y0", "side_y1")
_TV_VENTS = ("ventFront", "ventSide")


def _tv_ext_wall_T(T_amb_K: float, h: float) -> str:
    return (f"type            externalWallHeatFluxTemperature;\n"
            f"                mode            coefficient;\n"
            f"                Ta              uniform {T_amb_K:.2f};\n"
            f"                h               uniform {h:.4f};\n"
            f"                kappaMethod     fluidThermo;\n"
            f"                value           uniform {T_amb_K:.2f};")


def write_T_tv(p, zero_dir: Path) -> None:
    T_amb_K = p["ambient_C"] + 273.15
    h_floor, h_eff = _compute_h_eff(p)
    fan_on = p.get("fan_rpm", 0) > 1.0

    entries = []
    for w in _TV_WALLS:
        h = h_floor if w == "floor" else h_eff
        entries.append(f"            {w}\n            {{\n"
                       f"                {_tv_ext_wall_T(T_amb_K, h)}\n"
                       f"            }}")
    for v in _TV_VENTS:
        entries.append(f"            {v}\n            {{\n"
                       f"                type            inletOutlet;\n"
                       f"                inletValue      uniform {T_amb_K:.2f};\n"
                       f"                value           uniform {T_amb_K:.2f};\n"
                       f"            }}")
    if fan_on:
        entries.append(f"            fan\n            {{\n"
                       f"                type            inletOutlet;\n"
                       f"                inletValue      uniform {T_amb_K:.2f};\n"
                       f"                value           uniform {T_amb_K:.2f};\n"
                       f"            }}")
    else:
        entries.append(f"            fan\n            {{\n"
                       f"                {_tv_ext_wall_T(T_amb_K, h_eff)}\n"
                       f"            }}")

    body = "\n".join(entries)
    content = _foam_header("volScalarField", "T") + dedent(f"""\
        dimensions      [0 0 0 1 0 0 0];
        internalField   uniform {T_amb_K:.2f};

        boundaryField
        {{
{body}
        }}
        """)
    (zero_dir / "T").write_text(content)


def write_U_tv(p, zero_dir: Path) -> None:
    fan_on = p.get("fan_rpm", 0) > 1.0
    Q = fan_operating_flow(p)

    entries = [f"            {w} {{ type noSlip; }}" for w in _TV_WALLS]
    for v in _TV_VENTS:
        entries.append(f"            {v}\n            {{\n"
                       f"                type            pressureInletOutletVelocity;\n"
                       f"                value           uniform (0 0 0);\n"
                       f"            }}")
    if fan_on:
        # Negative volumetric rate = OUT of the domain (exhaust fan).
        # flowRateInletVelocity enforces the exact Q regardless of the
        # stair-stepped disk area created by cylinderToFace.
        entries.append(f"            fan\n            {{\n"
                       f"                type            flowRateInletVelocity;\n"
                       f"                volumetricFlowRate constant {-Q:.6e};\n"
                       f"                value           uniform (0 0 0);\n"
                       f"            }}")
    else:
        entries.append("            fan { type noSlip; }")

    body = "\n".join(entries)
    content = _foam_header("volVectorField", "U") + dedent(f"""\
        dimensions      [0 1 -1 0 0 0 0];
        internalField   uniform (0 0 0);

        boundaryField
        {{
{body}
        }}
        """)
    (zero_dir / "U").write_text(content)


def write_p_tv(p, zero_dir: Path) -> None:
    patches = list(_TV_WALLS) + list(_TV_VENTS) + ["fan"]
    body = "\n".join(
        f"            {name} {{ type calculated; value uniform 100000; }}"
        for name in patches)
    content = _foam_header("volScalarField", "p") + dedent(f"""\
        dimensions      [1 -1 -2 0 0 0 0];
        internalField   uniform 100000;

        boundaryField
        {{
{body}
        }}
        """)
    (zero_dir / "p").write_text(content)


def write_p_rgh_tv(p, zero_dir: Path) -> None:
    entries = [f"            {w} {{ type fixedFluxPressure; value uniform 100000; }}"
               for w in _TV_WALLS]
    for v in _TV_VENTS:
        # prghTotalPressure: ambient total pressure referenced to p_rgh —
        # correct open-boundary condition for buoyant solvers (handles the
        # rho*g*h offset that plain totalPressure would get wrong).
        entries.append(f"            {v}\n            {{\n"
                       f"                type            prghTotalPressure;\n"
                       f"                rho             rho;\n"
                       f"                p0              uniform 100000;\n"
                       f"                value           uniform 100000;\n"
                       f"            }}")
    entries.append("            fan { type fixedFluxPressure; value uniform 100000; }")

    body = "\n".join(entries)
    content = _foam_header("volScalarField", "p_rgh") + dedent(f"""\
        dimensions      [1 -1 -2 0 0 0 0];
        internalField   uniform 100000;

        boundaryField
        {{
{body}
        }}
        """)
    (zero_dir / "p_rgh").write_text(content)


def write_turbulence_fields_tv(p, zero_dir: Path) -> None:
    fan_on = p.get("fan_rpm", 0) > 1.0

    def block(wall_bc: str, open_bc: str, fan_closed_bc: str) -> str:
        lines = [f"            {w} {{ {wall_bc} }}" for w in _TV_WALLS]
        for v in _TV_VENTS:
            lines.append(f"            {v} {{ {open_bc} }}")
        lines.append(f"            fan {{ {open_bc if fan_on else fan_closed_bc} }}")
        return "\n".join(lines)

    fields = {
        "k": (
            "[0 2 -2 0 0 0 0]", "0.001",
            block("type kLowReWallFunction; value uniform 1e-10;",
                  "type inletOutlet; inletValue uniform 0.001; value uniform 0.001;",
                  "type zeroGradient;"),
        ),
        "omega": (
            "[0 0 -1 0 0 0 0]", "1.0",
            block("type omegaWallFunction; value uniform 1.0;",
                  "type inletOutlet; inletValue uniform 1.0; value uniform 1.0;",
                  "type zeroGradient;"),
        ),
        "epsilon": (
            "[0 2 -3 0 0 0 0]", "0.01",
            block("type epsilonWallFunction; value uniform 0.01;",
                  "type inletOutlet; inletValue uniform 0.01; value uniform 0.01;",
                  "type zeroGradient;"),
        ),
        "nut": (
            "[0 2 -1 0 0 0 0]", "0",
            block("type nutLowReWallFunction; value uniform 0;",
                  "type calculated; value uniform 0;",
                  "type calculated; value uniform 0;"),
        ),
        "alphat": (
            "[1 -1 -1 0 0 0 0]", "0",
            block("type compressible::alphatWallFunction; Prt 0.85; value uniform 0;",
                  "type calculated; value uniform 0;",
                  "type calculated; value uniform 0;"),
        ),
    }

    for name, (dims, init, body) in fields.items():
        content = _foam_header("volScalarField", name) + dedent(f"""\
            dimensions      {dims};
            internalField   uniform {init};
            boundaryField
            {{
{body}
            }}
            """)
        (zero_dir / name).write_text(content)


def write_thermophysical(constant_dir: Path) -> None:
    content = _foam_header("dictionary", "thermophysicalProperties") + dedent("""\
        thermoType
        {
            type            heRhoThermo;
            mixture         pureMixture;
            transport       const;
            thermo          hConst;
            equationOfState perfectGas;
            specie          specie;
            energy          sensibleEnthalpy;
        }

        mixture
        {
            specie
            {
                molWeight       28.96;
            }
            thermodynamics
            {
                Cp              1005;
                Hf              0;
            }
            transport
            {
                mu              1.84e-05;
                Pr              0.71;
            }
        }
        """)
    (constant_dir / "thermophysicalProperties").write_text(content)


def write_turbulence_properties(constant_dir: Path) -> None:
    content = _foam_header("dictionary", "turbulenceProperties") + dedent("""\
        simulationType  RAS;

        RAS
        {
            RASModel        kOmegaSST;
            turbulence      on;
            printCoeffs     on;
        }
        """)
    (constant_dir / "turbulenceProperties").write_text(content)


def write_g(constant_dir: Path) -> None:
    content = _foam_header("uniformDimensionedVectorField", "g") + dedent("""\
        dimensions      [0 1 -2 0 0 0 0];
        value           (0 0 -9.81);
        """)
    (constant_dir / "g").write_text(content)


def write_controlDict(p, system_dir: Path) -> None:
    n_iter = p.get("end_iter", 2000)
    write_int = p.get("write_interval", 500)
    content = _foam_header("dictionary", "controlDict") + dedent(f"""\
        application     buoyantSimpleFoam;
        startFrom       startTime;
        startTime       0;
        stopAt          endTime;
        endTime         {n_iter};
        deltaT          1;
        writeControl    timeStep;
        writeInterval   {write_int};
        purgeWrite      0;
        writeFormat     ascii;
        writePrecision  7;
        writeCompression off;
        timeFormat      general;
        timePrecision   6;
        runTimeModifiable true;
        """)
    if p.get("true_vents"):
        # The true vent/fan jets are quasi-unsteady (bounded residual
        # oscillation under SIMPLE), so report fields are iteration-averaged
        # over the second half of the run: TMean / UMean.
        avg_start = p.get("avg_start", n_iter // 2)
        content += dedent(f"""\

            functions
            {{
                fieldAverage1
                {{
                    type            fieldAverage;
                    libs            (fieldFunctionObjects);
                    writeControl    writeTime;
                    timeStart       {avg_start};
                    fields
                    (
                        T {{ mean on; prime2Mean off; base time; }}
                        U {{ mean on; prime2Mean off; base time; }}
                    );
                }}
            }}
            """)
    (system_dir / "controlDict").write_text(content)


def write_fvSchemes(system_dir: Path) -> None:
    content = _foam_header("dictionary", "fvSchemes") + dedent("""\
        ddtSchemes      { default steadyState; }
        gradSchemes     { default Gauss linear; }
        divSchemes
        {
            default                         none;
            div(phi,U)                      bounded Gauss linearUpwind grad(U);
            div(phi,K)                      bounded Gauss linear;
            div(phi,h)                      bounded Gauss linearUpwind grad(h);
            div(phi,k)                      bounded Gauss limitedLinear 1;
            div(phi,omega)                  bounded Gauss limitedLinear 1;
            div(phi,epsilon)                bounded Gauss limitedLinear 1;
            div(((rho*nuEff)*dev2(T(grad(U))))) Gauss linear;
        }
        laplacianSchemes { default Gauss linear corrected; }
        interpolationSchemes { default linear; }
        snGradSchemes   { default corrected; }
        wallDist        { method meshWave; }
        """)
    (system_dir / "fvSchemes").write_text(content)


def write_decomposeParDict(p, system_dir: Path) -> None:
    n = p.get("n_procs", 8)
    content = _foam_header("dictionary", "decomposeParDict") + dedent(f"""\
        numberOfSubdomains  {n};
        method              scotch;
        """)
    (system_dir / "decomposeParDict").write_text(content)


def write_fvSolution(system_dir: Path, tight: bool = False) -> None:
    """Write fvSolution.

    tight=False  → fan-on default (fast convergence on forced convection)
    tight=True   → fan-off / buoyancy-dominated case: tighter relaxation,
                   stricter p_rgh tolerance, longer-step h relaxation.
                   Required for natural-convection SIMPLE convergence.
    """
    if tight:
        U_relax       = 0.3
        scalar_relax  = 0.3
        field_relax   = 0.3
        p_rgh_resid   = "5e-4"
    else:
        U_relax       = 0.7
        scalar_relax  = 0.5
        field_relax   = 0.7
        p_rgh_resid   = "1e-3"

    content = _foam_header("dictionary", "fvSolution") + dedent(f"""\
        solvers
        {{
            p_rgh
            {{
                solver          GAMG;
                tolerance       1e-7;
                relTol          0.01;
                smoother        GaussSeidel;
            }}
            "(U|h|k|omega|epsilon)"
            {{
                solver          PBiCGStab;
                preconditioner  DILU;
                tolerance       1e-7;
                relTol          0.1;
            }}
        }}
        SIMPLE
        {{
            momentumPredictor   yes;
            nNonOrthogonalCorrectors 0;
            consistent          yes;
            pRefCell            0;
            pRefValue           100000;
            residualControl
            {{
                p_rgh           {p_rgh_resid};
                U               1e-4;
                h               1e-4;
                "(k|omega|epsilon)" 1e-3;
            }}
        }}
        relaxationFactors
        {{
            equations
            {{
                U               {U_relax};
                "(p_rgh|h|k|omega|epsilon)" {scalar_relax};
            }}
            fields
            {{
                p_rgh           {field_relax};
                rho             1.0;
            }}
        }}
        """)
    (system_dir / "fvSolution").write_text(content)


# ---------------------------------------------------------------------------
# Top-level entry
# ---------------------------------------------------------------------------

def generate_case(params: dict, target_dir: str | Path) -> Path:
    """Generate a complete OpenFOAM buoyantSimpleFoam case from params.

    Parameters
    ----------
    params : dict with keys
        wall_thickness_mm  : float
        wall_k             : float W/mK (PLA=0.2, aluminum=200)
        ambient_C          : float (e.g. 25.0)
        heat_total_W       : float (e.g. 17.0)
        mesh_nx, ny, nz    : int
        end_iter           : int (optional, default 2000)
        write_interval     : int (optional, default 500)
        h_ext              : float W/m2K external convection (optional)

    Returns
    -------
    Path : the case directory.
    """
    target = Path(target_dir).expanduser().resolve()
    target.mkdir(parents=True, exist_ok=True)

    true_vents = bool(params.get("true_vents"))

    # Fields go into 0.orig; the runner copies 0.orig -> 0 after the mesh
    # utilities (blockMesh / topoSet / createPatch) so the field boundary
    # entries always match the final patch list.
    zero_dir = target / "0.orig"
    constant_dir = target / "constant"
    system_dir = target / "system"
    for d in (zero_dir, constant_dir, system_dir):
        d.mkdir(exist_ok=True)

    # mesh + solver dicts
    write_blockMeshDict(params, system_dir)
    write_topoSetDict(params, system_dir)
    if true_vents:
        write_createPatchDict(params, system_dir)
    write_controlDict(params, system_dir)
    write_fvSchemes(system_dir)
    write_fvSolution(system_dir, tight=params.get("tight_relaxation", False))
    write_decomposeParDict(params, system_dir)

    # constant
    write_thermophysical(constant_dir)
    write_turbulence_properties(constant_dir)
    write_g(constant_dir)
    write_fvOptions(params, constant_dir)

    # initial fields
    if true_vents:
        write_T_tv(params, zero_dir)
        write_U_tv(params, zero_dir)
        write_p_tv(params, zero_dir)
        write_p_rgh_tv(params, zero_dir)
        write_turbulence_fields_tv(params, zero_dir)
    else:
        write_T(params, zero_dir)
        write_U(params, zero_dir)
        write_p(params, zero_dir)
        write_p_rgh(params, zero_dir)
        write_turbulence_fields(params, zero_dir)

    return target


if __name__ == "__main__":
    import sys

    target = sys.argv[1] if len(sys.argv) > 1 else "/tmp/plant_test"
    params = dict(
        wall_thickness_mm = 2.5,
        wall_k            = 0.20,
        ambient_C         = 25.0,
        heat_total_W      = 17.0,
        mesh_nx           = 36,
        mesh_ny           = 26,
        mesh_nz           = 20,
        end_iter          = 2000,
        write_interval    = 500,
    )
    case_dir = generate_case(params, target)
    print(f"Case generated at: {case_dir}")
    print(f"  files written:")
    for p in sorted(case_dir.rglob("*")):
        if p.is_file():
            print(f"    {p.relative_to(case_dir)}")
